version: "3"
services:
  web:
    image: nginx:1.15.6
    container_name: nginx
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: ./docker/php
    container_name: app
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: yamada
      MYSQL_PASSWORD: yamada
      MYSQL_ROOT_PASSWORD: yamada
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
